# Generated by Django 4.2.7 on 2023-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('built_in_memory', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('diagonal_screen', models.FloatField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
